/**
 * おんがく手帳：音楽用語データベース
 * データの追加・編集はこのファイルを更新するだけで完了します。
 */
export const INITIAL_TERMS = [
  // --- 強弱 (Dynamics: 1-49) ---
  { id: 1, term: 'Pianississimo', reading: 'ピアニッシッシモ', symbol: 'ppp', category: '強弱', lang: 'イタリア語', meaning: 'できるだけ弱く。', detail: '極限の弱音。消え入るような静寂。', color: 'bg-pink-50 text-pink-400' },
  { id: 2, term: 'Pianissimo', reading: 'ピアニッシモ', symbol: 'pp', category: '強弱', lang: 'イタリア語', meaning: 'とても弱く。', detail: '非常に弱い音量。繊細な場面。', color: 'bg-pink-100 text-pink-500' },
  { id: 3, term: 'Piano', reading: 'ピアノ', symbol: 'p', category: '強弱', lang: 'イタリア語', meaning: '弱く。', detail: '穏やかに。イタリア語で「静かに」。', color: 'bg-pink-200 text-pink-600' },
  { id: 4, term: 'Mezzo Piano', reading: 'メゾピアノ', symbol: 'mp', category: '強弱', lang: 'イタリア語', meaning: '少し弱く。', detail: '「半分のピアノ」。ピアノよりは芯がある。', color: 'bg-rose-50 text-rose-400' },
  { id: 5, term: 'Mezzo Forte', reading: 'メゾフォルテ', symbol: 'mf', category: '強弱', lang: 'イタリア語', meaning: '少し強く。', detail: '日常的な話し声程度の強さ。', color: 'bg-orange-50 text-orange-400' },
  { id: 6, term: 'Forte', reading: 'フォルテ', symbol: 'f', category: '強弱', lang: 'イタリア語', meaning: '強く。', detail: '情熱や意志の強さを表現。', color: 'bg-orange-100 text-orange-500' },
  { id: 7, term: 'Fortissimo', reading: 'フォルティッシモ', symbol: 'ff', category: '強弱', lang: 'イタリア語', meaning: 'とても強く。', detail: '圧倒的なエネルギー。', color: 'bg-red-100 text-red-500' },
  { id: 8, term: 'Fortississimo', reading: 'フォルティッシッシモ', symbol: 'fff', category: '強弱', lang: 'イタリア語', meaning: 'できるだけ強く。', detail: '最大の音量。爆発的な感情。', color: 'bg-red-200 text-red-600' },
  { id: 9, term: 'Crescendo', reading: 'クレッシェンド', symbol: '<', category: '強弱', lang: 'イタリア語', meaning: 'だんだん強く。', detail: '徐々に音量を増し盛り上がりを作る。', color: 'bg-rose-50 text-rose-500' },
  { id: 10, term: 'Decrescendo', reading: 'デクレッシェンド', symbol: '>', category: '強弱', lang: 'イタリア語', meaning: 'だんだん弱く。', detail: '徐々に音量を落とし静寂へ向かう。', color: 'bg-slate-50 text-slate-400' },
  { id: 11, term: 'Diminuendo', reading: 'ディミヌエンド', symbol: 'dim.', category: '強弱', lang: 'イタリア語', meaning: 'だんだん弱く。', detail: '音を減衰させ表情を和らげる。', color: 'bg-slate-100 text-slate-500' },
  { id: 12, term: 'Sforzando', reading: 'スフォルツァンド', symbol: 'sfz', category: '強弱', lang: 'イタリア語', meaning: 'その音だけ強く。', detail: '特定の音を鋭く強調する。', color: 'bg-red-50 text-red-400' },
  { id: 13, term: 'Forte Piano', reading: 'フォルテピアノ', symbol: 'fp', category: '強弱', lang: 'イタリア語', meaning: '強く、すぐに弱く。', detail: '強いアタックの直後に急落させる。', color: 'bg-purple-50 text-purple-400' },
  { id: 14, term: 'Rinforzando', reading: 'リンフォルツァンド', symbol: 'rfz', category: '強弱', lang: 'イタリア語', meaning: '急に強く。', detail: '短い句やフレーズを一段と強調。', color: 'bg-indigo-50 text-indigo-400' },
  { id: 15, term: 'Forzato', reading: 'フォルツァート', symbol: 'fz', category: '強弱', lang: 'イタリア語', meaning: '強く、強調して。', detail: '特にその音を際立たせる。', color: 'bg-red-50' },
  { id: 16, term: 'Sforzato Piano', reading: 'スフォルツァート・ピアノ', symbol: 'sfzp', category: '強弱', lang: 'イタリア語', meaning: 'アクセント後すぐに弱く。', detail: '鋭い攻撃の後に即座に減衰。', color: 'bg-purple-100' },
  { id: 17, term: 'Poco Forte', reading: 'ポーコ・フォルテ', symbol: 'pf', category: '強弱', lang: 'イタリア語', meaning: '少し強く。', detail: 'mfより少し強めのニュアンス。', color: 'bg-orange-50' },
  { id: 18, term: 'Calando', reading: 'カランド', symbol: 'calando', category: '強弱', lang: 'イタリア語', meaning: '弱めながら遅く。', detail: '音量と速度を同時に落とす。', color: 'bg-blue-50 text-blue-400' },
  { id: 19, term: 'Morendo', reading: 'モレンド', symbol: 'morendo', category: '強弱', lang: 'イタリア語', meaning: '絶え入るように。', detail: '音が消滅していくように。', color: 'bg-slate-200' },
  { id: 20, term: 'Smorzando', reading: 'スモルツァンド', symbol: 'smorz.', category: '強弱', lang: 'イタリア語', meaning: '消えゆくように。', detail: '音を和らげ次第に消していく。', color: 'bg-stone-100' },
  { id: 21, term: 'Perdendosi', reading: 'ペルデンドシ', symbol: 'perd.', category: '強弱', lang: 'イタリア語', meaning: '消えゆくように。', detail: '音が薄れていく様を表現。', color: 'bg-blue-50' },
  { id: 22, term: 'Sotto voce', reading: 'ソット・ヴォーチェ', symbol: 'sotto voce', category: '強弱', lang: 'イタリア語', meaning: '声をひそめて。', detail: '抑えられた内省的なトーン。', color: 'bg-blue-50 text-blue-400' },
  { id: 23, term: 'Mezzo voce', reading: 'メゾ・ヴォーチェ', symbol: 'm.v.', category: '強弱', lang: 'イタリア語', meaning: '中くらいの声で。', detail: '抑制を効かせた響き。', color: 'bg-teal-50' },
  { id: 24, term: 'Al niente', reading: 'アル・ニエンテ', symbol: null, category: '強弱', lang: 'イタリア語', meaning: '完全に無になるまで。', detail: '音が聞こえなくなるまで。', color: 'bg-slate-50' },

  // --- 速度 (Tempo: 50-129) ---
  { id: 50, term: 'Larghissimo', reading: 'ラルギッシモ', symbol: null, category: '速度', lang: 'イタリア語', meaning: 'きわめて幅広く。', detail: '最も遅い速度指定。', color: 'bg-slate-900 text-white' },
  { id: 51, term: 'Grave', reading: 'グラーヴェ', symbol: null, category: '速度', lang: 'イタリア語', meaning: '重々しく。', detail: '荘厳で非常に遅い速度。', color: 'bg-slate-800 text-white' },
  { id: 52, term: 'Largo', reading: 'ラルゴ', symbol: null, category: '速度', lang: 'イタリア語', meaning: '幅広く。', detail: 'ゆったりした広大な流れ。', color: 'bg-emerald-50 text-emerald-700' },
  { id: 53, term: 'Larghetto', reading: 'ラルゲット', symbol: null, category: '速度', lang: 'イタリア語', meaning: '少し幅広く。', detail: 'Largoより少しだけ速い。', color: 'bg-emerald-100' },
  { id: 54, term: 'Adagio', reading: 'アダージョ', symbol: null, category: '速度', lang: 'イタリア語', meaning: 'ゆるやかに。', detail: '落ち着いてくつろいだ速度。', color: 'bg-cyan-50 text-cyan-600' },
  { id: 55, term: 'Adagietto', reading: 'アダージェット', symbol: null, category: '速度', lang: 'イタリア語', meaning: 'やや速く。', detail: 'Adagioより少し速い。', color: 'bg-blue-50' },
  { id: 56, term: 'Lento', reading: 'レント', symbol: null, category: '速度', lang: 'イタリア語', meaning: '遅く。', detail: 'ゆったりした遅さ。', color: 'bg-teal-50' },
  { id: 57, term: 'Andante', reading: 'アンダンテ', symbol: null, category: '速度', lang: 'イタリア語', meaning: '歩くように。', detail: '自然な歩みの遅さ。', color: 'bg-green-50 text-green-600' },
  { id: 58, term: 'Andantino', reading: 'アンダンティーノ', symbol: null, category: '速度', lang: 'イタリア語', meaning: '少し速く。', detail: 'Andanteより少し活発。', color: 'bg-lime-50' },
  { id: 59, term: 'Moderato', reading: 'モデラート', symbol: 'Mod.', category: '速度', lang: 'イタリア語', meaning: '中くらいの速さ。', detail: '標準的なテンポ。', color: 'bg-yellow-50 text-yellow-600' },
  { id: 60, term: 'Allegretto', reading: 'アレグレット', symbol: null, category: '速度', lang: 'イタリア語', meaning: 'やや速く。', detail: '軽快で弾むような速度。', color: 'bg-amber-50 text-amber-600' },
  { id: 61, term: 'Allegro', reading: 'アレグロ', symbol: null, category: '速度', lang: 'イタリア語', meaning: '速く、陽気に。', detail: '快活でエネルギーに満ちた。', color: 'bg-orange-50 text-orange-600' },
  { id: 62, term: 'Vivace', reading: 'ヴィヴァーチェ', symbol: null, category: '速度', lang: 'イタリア語', meaning: '速く、生き生き。', detail: '躍動感のある速度。', color: 'bg-red-50 text-red-500' },
  { id: 63, term: 'Vivo', reading: 'ヴィーヴォ', symbol: null, category: '速度', lang: 'イタリア語', meaning: '速く。', detail: '生命力あふれる速い速度。', color: 'bg-orange-100' },
  { id: 64, term: 'Presto', reading: 'プレスト', symbol: null, category: '速度', lang: 'イタリア語', meaning: 'きわめて速く。', detail: '全力疾走するようなテンポ。', color: 'bg-rose-50 text-rose-600' },
  { id: 65, term: 'Prestissimo', reading: 'プレスティッシモ', symbol: null, category: '速度', lang: 'イタリア語', meaning: '最高速で。', detail: '技巧の限界に近い猛烈な速さ。', color: 'bg-red-200' },
  { id: 66, term: 'Ritardando', reading: 'リタルダンド', symbol: 'rit.', category: '速度', lang: 'イタリア語', meaning: 'だんだん遅く。', detail: '速度を徐々に落とす。', color: 'bg-stone-50' },
  { id: 67, term: 'Rallentando', reading: 'ラレンタンド', symbol: 'rall.', category: '速度', lang: 'イタリア語', meaning: 'だんだん遅く。', detail: 'rit.より緩やかに弛緩する。', color: 'bg-stone-100' },
  { id: 68, term: 'Accelerando', reading: 'アッチェレランド', symbol: 'accel.', category: '速度', lang: 'イタリア語', meaning: 'だんだん速く。', detail: '徐々に加速していく。', color: 'bg-blue-50' },
  { id: 69, term: 'A tempo', reading: 'ア・テンポ', symbol: 'a tempo', category: '速度', lang: 'イタリア語', meaning: '元の速さで。', detail: '変化を解除し元のテンポへ。', color: 'bg-sky-50' },
  { id: 70, term: 'Tempo Primo', reading: 'テンポ・プリモ', symbol: 'T.P.', category: '速度', lang: 'イタリア語', meaning: '最初の速さで。', detail: '曲の冒頭のテンポに戻る。', color: 'bg-indigo-50' },
  { id: 71, term: 'Meno mosso', reading: 'メノ・モッソ', symbol: null, category: '速度', lang: 'イタリア語', meaning: '今までより遅く。', detail: '動きを少なくして緩やかに。', color: 'bg-slate-100' },
  { id: 72, term: 'Più mosso', reading: 'ピュ・モッソ', symbol: null, category: '速度', lang: 'イタリア語', meaning: '今までより速く。', detail: '動きを増して活発に。', color: 'bg-orange-100' },
  { id: 73, term: 'Stringendo', reading: 'ストリンジェンド', symbol: 'string.', category: '速度', lang: 'イタリア語', meaning: '速くせき立てて。', detail: '緊張感を高めながら加速。', color: 'bg-red-50' },
  { id: 74, term: 'Allargando', reading: 'アラルガンド', symbol: 'allarg.', category: '速度', lang: 'イタリア語', meaning: '強くしながら遅く。', detail: '最高潮へ向け速度を落とす。', color: 'bg-orange-100' },
  { id: 75, term: 'Tempo giusto', reading: 'テンポ・ジュスト', symbol: null, category: '速度', lang: 'イタリア語', meaning: '正確な速さで。', detail: 'ふさわしい妥当な速度。', color: 'bg-blue-50' },
  { id: 76, term: 'Rubato', reading: 'ルバート', symbol: null, category: '速度', lang: 'イタリア語', meaning: '自由に。', detail: '旋律のテンポを自由に伸縮。', color: 'bg-indigo-50' },
  { id: 77, term: 'Schnell', reading: 'シュネル', symbol: null, category: '速度', lang: 'ドイツ語', meaning: '速く。', detail: 'イタリア語のAllegro。', color: 'bg-orange-200' },
  { id: 78, term: 'Langsam', reading: 'ラングザム', symbol: null, category: '速度', lang: 'ドイツ語', meaning: '遅く。', detail: 'イタリア語のLento。', color: 'bg-neutral-200' },

  // --- 奏法 (Technique: 130-199) ---
  { id: 130, term: 'Legato', reading: 'レガート', symbol: '〜', category: '奏法', lang: 'イタリア語', meaning: 'なめらかに。', detail: '音の境目をなくし繋ぐ。', color: 'bg-blue-100 text-blue-600' },
  { id: 131, term: 'Staccato', reading: 'スタッカート', symbol: '・', category: '奏法', lang: 'イタリア語', meaning: '短く切って。', detail: '音を切り離し軽快に跳ねる。', color: 'bg-indigo-100 text-indigo-600' },
  { id: 132, term: 'Tenuto', reading: 'テヌート', symbol: '-', category: '奏法', lang: 'イタリア語', meaning: '音を保って。', detail: '音を最後までしっかり響かせる。', color: 'bg-violet-100 text-violet-600' },
  { id: 133, term: 'Fermata', reading: 'フェルマータ', symbol: '𝄐', category: '奏法', lang: 'イタリア語', meaning: 'ほどよく延ばす。', detail: '一時停止して余韻を楽しむ。', color: 'bg-fuchsia-100 text-fuchsia-600' },
  { id: 134, term: 'Pizzicato', reading: 'ピッツィカート', symbol: 'pizz.', category: '奏法', lang: 'イタリア語', meaning: '弦を弾く。', detail: '指で弦をはじいて音を出す。', color: 'bg-amber-100' },
  { id: 135, term: 'Arco', reading: 'アルコ', symbol: 'arco', category: '奏法', lang: 'イタリア語', meaning: '弓で。', detail: '再び弓を使って演奏する。', color: 'bg-slate-200' },
  { id: 136, term: 'Glissando', reading: 'グリッサンド', symbol: 'gliss.', category: '奏法', lang: 'イタリア語', meaning: '滑らせて。', detail: '高さを連続的に変化させる。', color: 'bg-cyan-100' },
  { id: 137, term: 'Trill', reading: 'トリル', symbol: 'tr', category: '奏法', lang: 'イタリア語', meaning: '震わせて。', detail: '隣接音を高速で反復させる。', color: 'bg-yellow-50' },
  { id: 138, term: 'Marcato', reading: 'マルカート', symbol: 'marc.', category: '奏法', lang: 'イタリア語', meaning: 'はっきりと。', detail: '一つ一つの音を力強く。', color: 'bg-slate-300' },
  { id: 139, term: 'Sostenuto', reading: 'ソステヌート', symbol: 'sost.', category: '奏法', lang: 'イタリア語', meaning: '十分に保持。', detail: '響きを豊かに保ち重厚に。', color: 'bg-blue-50' },
  { id: 140, term: 'Tutti', reading: 'トゥッティ', symbol: 'tutti', category: '奏法', lang: 'イタリア語', meaning: '全員で。', detail: '合奏者全員での演奏。', color: 'bg-blue-200' },
  { id: 141, term: 'Solo', reading: 'ソロ', symbol: 'solo', category: '奏法', lang: 'イタリア語', meaning: '独奏。', detail: '一人の奏者が主役となる。', color: 'bg-yellow-200' },
  { id: 142, term: 'Vibrato', reading: 'ヴィブラート', symbol: 'vib.', category: '奏法', lang: 'イタリア語', meaning: '震わせて。', detail: 'ピッチを微細に揺らし響かせる。', color: 'bg-purple-50' },
  { id: 143, term: 'Appoggiatura', reading: 'アッポジャトゥーラ', symbol: null, category: '奏法', lang: 'イタリア語', meaning: '前打音。', detail: '主音の前に付く装飾音。', color: 'bg-rose-50' },
  { id: 144, term: 'Portato', reading: 'ポルタート', symbol: null, category: '奏法', lang: 'イタリア語', meaning: '柔らかく切る。', detail: 'レガートとスタッカートの中間。', color: 'bg-indigo-50' },

  // --- 表情 (Expression: 200-399) ---
  { id: 200, term: 'Dolce', reading: 'ドルチェ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '甘く、優しく。', detail: '愛らしく柔らかな表情で。', color: 'bg-pink-50 text-pink-400' },
  { id: 201, term: 'Cantabile', reading: 'カンタービレ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '歌うように。', detail: '旋律を表情豊かに響かせる。', color: 'bg-indigo-50 text-indigo-500' },
  { id: 202, term: 'Agitato', reading: 'アジタート', symbol: null, category: '表情', lang: 'イタリア語', meaning: '激しく、興奮して。', detail: '情熱的で落ち着かない表現。', color: 'bg-red-50 text-red-600' },
  { id: 203, term: 'Maestoso', reading: 'マエストーゾ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '堂々と、荘厳に。', detail: '立派で誇り高い雰囲気。', color: 'bg-slate-200 text-slate-700' },
  { id: 204, term: 'Tranquillo', reading: 'トランクィッロ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '静かに、穏やかに。', detail: '平和で落ち着いた気分。', color: 'bg-cyan-50 text-cyan-500' },
  { id: 205, term: 'Espressivo', reading: 'エスプレッシーヴォ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '表情豊かに。', detail: '感情をたっぷり込めて。', color: 'bg-rose-50 text-rose-600' },
  { id: 206, term: 'Grazioso', reading: 'グラツィオーゾ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '優雅に、上品に。', detail: '洗練された美しさ。', color: 'bg-purple-50 text-purple-500' },
  { id: 207, term: 'Amabile', reading: 'アマービレ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '愛らしく。', detail: '親しみやすく可愛い。', color: 'bg-pink-100' },
  { id: 208, term: 'Appassionato', reading: 'アパッショナート', symbol: null, category: '表情', lang: 'イタリア語', meaning: '熱情的に。', detail: '深い感情と激しさを伴う。', color: 'bg-red-500 text-white' },
  { id: 209, term: 'Brillante', reading: 'ブリランテ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '輝かしく。', detail: '華やかで技巧的な明るさ。', color: 'bg-yellow-100 text-amber-600' },
  { id: 210, term: 'Capriccioso', reading: 'カプリッチョーゾ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '気まぐれに。', detail: '自由な遊び心のある表現。', color: 'bg-orange-100' },
  { id: 211, term: 'Feroce', reading: 'フェローチェ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '荒々しく。', detail: '攻撃的で野生的な強さ。', color: 'bg-red-900 text-white' },
  { id: 212, term: 'Giocoso', reading: 'ジョコーゾ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '楽しげに。', detail: '愉快で明るい遊び心。', color: 'bg-lime-400' },
  { id: 213, term: 'Lamentoso', reading: 'ラメントーゾ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '悲しげに。', detail: '嘆き悲しむような重さ。', color: 'bg-slate-600 text-white' },
  { id: 214, term: 'Misterioso', reading: 'ミステリオーゾ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '神秘的に。', detail: '謎めいた不思議な雰囲気。', color: 'bg-indigo-900 text-white' },
  { id: 215, term: 'Nobile', reading: 'ノービレ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '高貴に。', detail: '気高く品格のある表現。', color: 'bg-yellow-50 text-amber-700' },
  { id: 216, term: 'Pesante', reading: 'ペザンテ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '重々しく。', detail: '踏みしめるような重さ。', color: 'bg-stone-500 text-white' },
  { id: 217, term: 'Risoluto', reading: 'リゾルート', symbol: null, category: '表情', lang: 'イタリア語', meaning: '決然と。', detail: 'きっぱりとした意志の強さ。', color: 'bg-indigo-400 text-white' },
  { id: 218, term: 'Scherzando', reading: 'スケルツァンド', symbol: null, category: '表情', lang: 'イタリア語', meaning: 'おどけて。', detail: 'ユーモアのある軽快な表現。', color: 'bg-yellow-100 text-yellow-700' },
  { id: 219, term: 'Tenero', reading: 'テーネロ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '優しく。', detail: '愛情深く柔らかな表現。', color: 'bg-rose-100' },
  { id: 220, term: 'Visionario', reading: 'ヴィジオナリオ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '幻想的に。', detail: '夢を見ているような。', color: 'bg-indigo-50' },
  { id: 221, term: 'Freddo', reading: 'フレッド', symbol: null, category: '表情', lang: 'イタリア語', meaning: '冷たく。', detail: '感情を抑えた無機質な響き。', color: 'bg-blue-50' },
  { id: 222, term: 'Luminoso', reading: 'ルミノーゾ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '光輝いて。', detail: '明るく透明感のある音。', color: 'bg-yellow-200' },
  { id: 223, term: 'Oscuro', reading: 'オスクーロ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '暗く。', detail: '不透明で重苦しい響き。', color: 'bg-black text-white' },
  { id: 224, term: 'Svegliando', reading: 'ズヴェリアンド', symbol: null, category: '表情', lang: 'イタリア語', meaning: '目を覚まして。', detail: '眠りから覚めたような動き。', color: 'bg-sky-200' },
  { id: 225, term: 'Ardente', reading: 'アルデンテ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '燃えるように。', detail: '激しく情熱的な演奏。', color: 'bg-red-400 text-white' },
  { id: 226, term: 'Bizzarro', reading: 'ビッツァーロ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '風変わりな。', detail: '奇妙で独特な表現。', color: 'bg-stone-100' },
  { id: 227, term: 'Lietamente', reading: 'リエタメンテ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '楽しく。', detail: '満足した喜びを持って。', color: 'bg-orange-50' },
  { id: 228, term: 'Parlante', reading: 'パルランテ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '語るように。', detail: '言葉を話すような抑揚。', color: 'bg-emerald-50' },
  { id: 229, term: 'Timoroso', reading: 'ティモローゾ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '恐る恐る。', detail: '怯えたような震える響き。', color: 'bg-blue-50' },
  { id: 230, term: 'Vuoto', reading: 'ヴオート', symbol: null, category: '表情', lang: 'イタリア語', meaning: '空っぽの。', detail: '空虚な、中身のない響き。', color: 'bg-slate-50' },

  // --- 構成 (Structure: 450-499) ---
  { id: 450, term: 'Fine', reading: 'フィーネ', symbol: 'Fine', category: '構成', lang: 'イタリア語', meaning: '終わり。', detail: '楽曲の終了地点。', color: 'bg-slate-300 text-slate-800' },
  { id: 451, term: 'Da Capo', reading: 'ダ・カーポ', symbol: 'D.C.', category: '構成', lang: 'イタリア語', meaning: '最初へ。', detail: '冒頭に戻る。', color: 'bg-neutral-100 text-neutral-600' },
  { id: 452, term: 'Dal Segno', reading: 'ダル・セーニョ', symbol: 'D.S.', category: '構成', lang: 'イタリア語', meaning: 'セーニョへ。', detail: '記号まで戻る。', color: 'bg-neutral-200 text-neutral-700' },
  { id: 453, term: 'Coda', reading: 'コーダ', symbol: '𝄌', category: '構成', lang: 'イタリア語', meaning: '結び。', detail: '独立した終結部。', color: 'bg-slate-200 text-slate-600' },
  { id: 454, term: 'Segno', reading: 'セーニョ', symbol: '𝄋', category: '構成', lang: 'イタリア語', meaning: '標識。', detail: '繰り返しの印。', color: 'bg-neutral-100 text-neutral-500' },
  { id: 455, term: 'Repeat', reading: 'リピート', symbol: ':||', category: '構成', lang: '英語', meaning: '繰り返し。', detail: '指定区間を再演。', color: 'bg-neutral-50 text-neutral-400' },
  { id: 456, term: 'Attacca', reading: 'アッタッカ', symbol: 'Attacca', category: '構成', lang: 'イタリア語', meaning: '続けて。', detail: '休みなく次へ進む。', color: 'bg-red-50 text-red-500' },
  { id: 457, term: 'Segue', reading: 'セーグエ', symbol: 'segue', category: '構成', lang: 'イタリア語', meaning: '切れ目なく続く。', detail: 'そのまま次へ移行。', color: 'bg-blue-50' },
  { id: 458, term: 'Volti subito', reading: 'ヴォルティ・スビト', symbol: 'V.S.', category: '構成', lang: 'イタリア語', meaning: 'すぐに譜をめくれ。', detail: '休みのない曲のページめくり指示。', color: 'bg-amber-50' },
  { id: 459, term: 'Generalpause', reading: 'ゲネラルパウゼ', symbol: 'G.P.', category: '構成', lang: 'ドイツ語', meaning: '全休止。', detail: '全奏者が一斉に休む部分。', color: 'bg-slate-900 text-white' },
];
