// --- 大規模音楽用語データベース (207語 完全版) ---
// 将来的に8000語まで拡張する際、この配列に追記していきます。
export const INITIAL_TERMS = [
  // --- 強弱 (Dynamics) ---
  { id: 1, term: 'Pianississimo', reading: 'ピアニッシッシモ', symbol: 'ppp', category: '強弱', lang: 'イタリア語', meaning: 'できるだけ弱く。', detail: '極限の弱音。消え入るような静寂を表現。', color: 'bg-pink-50 text-pink-400' },
  { id: 2, term: 'Pianissimo', reading: 'ピアニッシモ', symbol: 'pp', category: '強弱', lang: 'イタリア語', meaning: 'とても弱く。', detail: '非常に弱い音量。繊細な内省的場面に。', color: 'bg-pink-100 text-pink-500' },
  { id: 3, term: 'Piano', reading: 'ピアノ', symbol: 'p', category: '強弱', lang: 'イタリア語', meaning: '弱く。', detail: '穏やかに。イタリア語で「静かに」の意味。', color: 'bg-pink-200 text-pink-600' },
  { id: 4, term: 'Mezzo Piano', reading: 'メゾピアノ', symbol: 'mp', category: '強弱', lang: 'イタリア語', meaning: '少し弱く。', detail: '「半分のピアノ」。ピアノよりは芯のある音量。', color: 'bg-rose-50 text-rose-400' },
  { id: 5, term: 'Mezzo Forte', reading: 'メゾフォルテ', symbol: 'mf', category: '強弱', lang: 'イタリア語', meaning: '少し強く。', detail: '「半分のフォルテ」。日常的な話し声程度の強さ。', color: 'bg-orange-50 text-orange-400' },
  { id: 6, term: 'Forte', reading: 'フォルテ', symbol: 'f', category: '強弱', lang: 'イタリア語', meaning: '強く。', detail: '力強く、堂々と。情熱や意志の強さを表現。', color: 'bg-orange-100 text-orange-500' },
  { id: 7, term: 'Fortissimo', reading: 'フォルティッシモ', symbol: 'ff', category: '強弱', lang: 'イタリア語', meaning: 'とても強く。', detail: 'フォルテよりさらに強く。圧倒的なエネルギー。', color: 'bg-red-100 text-red-500' },
  { id: 8, term: 'Fortississimo', reading: 'フォルティッシッシモ', symbol: 'fff', category: '強弱', lang: 'イタリア語', meaning: 'できるだけ強く。', detail: '最大の音量。爆発的な感情や全合奏に。', color: 'bg-red-200 text-red-600' },
  { id: 9, term: 'Crescendo', reading: 'クレッシェンド', symbol: '<', category: '強弱', lang: 'イタリア語', meaning: 'だんだん強く。', detail: '徐々に音量を増し、盛り上がりを作ります。', color: 'bg-rose-50 text-rose-500' },
  { id: 10, term: 'Decrescendo', reading: 'デクレッシェンド', symbol: '>', category: '強弱', lang: 'イタリア語', meaning: 'だんだん弱く。', detail: '徐々に音量を落とし、静寂へ向かいます。', color: 'bg-slate-50 text-slate-400' },
  { id: 11, term: 'Diminuendo', reading: 'ディミヌエンド', symbol: 'dim.', category: '強弱', lang: 'イタリア語', meaning: 'だんだん弱く。', detail: '音を減衰させ、表情を和らげます。', color: 'bg-slate-100 text-slate-500' },
  { id: 12, term: 'Sforzando', reading: 'スフォルツァンド', symbol: 'sfz', category: '強弱', lang: 'イタリア語', meaning: 'その音だけ強く。', detail: '特定の音を鋭く強調し強い衝撃を与えます。', color: 'bg-red-50 text-red-400' },
  { id: 13, term: 'Forte Piano', reading: 'フォルテピアノ', symbol: 'fp', category: '強弱', lang: 'イタリア語', meaning: '強く、すぐに弱く。', detail: '強いアタックの直後に急落させる表現。', color: 'bg-purple-50 text-purple-400' },
  { id: 14, term: 'Rinforzando', reading: 'リンフォルツァンド', symbol: 'rfz', category: '強弱', lang: 'イタリア語', meaning: '急に強く。', detail: '短い句やフレーズを一段と強調します。', color: 'bg-indigo-50 text-indigo-400' },
  { id: 15, term: 'Calando', reading: 'カランド', symbol: 'calando', category: '強弱', lang: 'イタリア語', meaning: '弱めながら遅く。', detail: '音量と速度を同時に落とし、静かに沈む表現。', color: 'bg-blue-50 text-blue-400' },
  { id: 16, term: 'Morendo', reading: 'モレンド', symbol: 'morendo', category: '強弱', lang: 'イタリア語', meaning: '絶え入るように。', detail: '音を消滅させていく、極めて静かな終わり。', color: 'bg-slate-200 text-slate-500' },
  { id: 17, term: 'Smorzando', reading: 'スモルツァンド', symbol: 'smorz.', category: '強弱', lang: 'イタリア語', meaning: '消えゆくように。', detail: '音を和らげ、次第に消していく表現。', color: 'bg-stone-100 text-stone-500' },
  { id: 18, term: 'Perdendosi', reading: 'ペルデンドシ', symbol: 'perd.', category: '強弱', lang: 'イタリア語', meaning: '消えゆくように。', detail: '音が薄れていく様を表現。', color: 'bg-blue-50 text-blue-300' },
  { id: 19, term: 'Sotto voce', reading: 'ソット・ヴォーチェ', symbol: 'sotto voce', category: '強弱', lang: 'イタリア語', meaning: '声をひそめて。', detail: '抑えられた神秘的なトーンでの演奏。', color: 'bg-blue-50 text-blue-400' },

  // --- 速度 (Tempo) ---
  { id: 20, term: 'Larghissimo', reading: 'ラルギッシモ', symbol: null, category: '速度', lang: 'イタリア語', meaning: 'きわめて幅広く。', detail: '最も遅い速度指定。', color: 'bg-slate-900 text-white' },
  { id: 21, term: 'Grave', reading: 'グラーヴェ', symbol: null, category: '速度', lang: 'イタリア語', meaning: '重々しく。', detail: '荘厳で非常に遅い速度指定。', color: 'bg-slate-800 text-white' },
  { id: 22, term: 'Largo', reading: 'ラルゴ', symbol: null, category: '速度', lang: 'イタリア語', meaning: '幅広く。', detail: 'ゆったりした広大な流れを感じさせる速度。', color: 'bg-emerald-50 text-emerald-700' },
  { id: 23, term: 'Larghetto', reading: 'ラルゲット', symbol: null, category: '速度', lang: 'イタリア語', meaning: '少し幅広く。', detail: 'Largoより少しだけ速い速度。', color: 'bg-emerald-100' },
  { id: 24, term: 'Adagio', reading: 'アダージョ', symbol: null, category: '速度', lang: 'イタリア語', meaning: 'ゆるやかに。', detail: '落ち着いてくつろいだ速度。', color: 'bg-cyan-50 text-cyan-600' },
  { id: 25, term: 'Adagietto', reading: 'アダージェット', symbol: null, category: '速度', lang: 'イタリア語', meaning: 'やや速く。', detail: 'Adagioより少し速い速度。', color: 'bg-blue-50' },
  { id: 26, term: 'Lento', reading: 'レント', symbol: null, category: '速度', lang: 'イタリア語', meaning: '遅く。', detail: 'ゆったりした遅さ。瞑想的な場面。', color: 'bg-teal-50' },
  { id: 27, term: 'Andante', reading: 'アンダンテ', symbol: null, category: '速度', lang: 'イタリア語', meaning: '歩くように。', detail: '自然な歩みの遅さ。穏やかな速さ。', color: 'bg-green-50 text-green-600' },
  { id: 28, term: 'Andantino', reading: 'アンダンティーノ', symbol: null, category: '速度', lang: 'イタリア語', meaning: '少し速く。', detail: 'Andanteより少し活発な速度。', color: 'bg-lime-50' },
  { id: 29, term: 'Moderato', reading: 'モデラート', symbol: 'Mod.', category: '速度', lang: 'イタリア語', meaning: '中くらいの速さ。', detail: '標準的なテンポ。', color: 'bg-yellow-50 text-yellow-600' },
  { id: 30, term: 'Allegretto', reading: 'アレグレット', symbol: null, category: '速度', lang: 'イタリア語', meaning: 'やや速く。', detail: '軽快で弾むような速度。', color: 'bg-amber-50 text-amber-600' },
  { id: 31, term: 'Allegro', reading: 'アレグロ', symbol: null, category: '速度', lang: 'イタリア語', meaning: '速く、陽気に。', detail: '快活でエネルギーに満ちたテンポ。', color: 'bg-orange-50 text-orange-600' },
  { id: 32, term: 'Vivace', reading: 'ヴィヴァーチェ', symbol: null, category: '速度', lang: 'イタリア語', meaning: '速く、生き生き。', detail: '躍動感のある速度。', color: 'bg-red-50 text-red-500' },
  { id: 33, term: 'Vivo', reading: 'ヴィーヴォ', symbol: null, category: '速度', lang: 'イタリア語', meaning: '速く。', detail: '生命力あふれる速い速度。', color: 'bg-orange-100' },
  { id: 34, term: 'Presto', reading: 'プレスト', symbol: null, category: '速度', lang: 'イタリア語', meaning: 'きわめて速く。', detail: '全力疾走するようなテンポ。', color: 'bg-rose-50 text-rose-600' },
  { id: 35, term: 'Prestissimo', reading: 'プレスティッシモ', symbol: null, category: '速度', lang: 'イタリア語', meaning: '最高速で。', detail: '技巧の限界に近い猛烈な速さ。', color: 'bg-red-200 text-red-700' },
  { id: 36, term: 'Ritardando', reading: 'リタルダンド', symbol: 'rit.', category: '速度', lang: 'イタリア語', meaning: 'だんだん遅く。', detail: '速度を徐々に落とします。', color: 'bg-stone-50' },
  { id: 37, term: 'Rallentando', reading: 'ラレンタンド', symbol: 'rall.', category: '速度', lang: 'イタリア語', meaning: 'だんだん遅く。', detail: 'rit.より緩やかに弛緩する様。', color: 'bg-stone-100' },
  { id: 38, term: 'Accelerando', reading: 'アッチェレランド', symbol: 'accel.', category: '速度', lang: 'イタリア語', meaning: 'だんだん速く。', detail: '徐々に加速し高揚感を作る。', color: 'bg-blue-50' },
  { id: 39, term: 'A tempo', reading: 'ア・テンポ', symbol: 'a tempo', category: '速度', lang: 'イタリア語', meaning: '元の速さで。', detail: '変化を解除し元のテンポへ。', color: 'bg-sky-50' },
  { id: 40, term: 'Tempo Primo', reading: 'テンポ・プリモ', symbol: 'T.P.', category: '速度', lang: 'イタリア語', meaning: '最初の速さで。', detail: '曲の冒頭のテンポに戻る。', color: 'bg-indigo-50' },
  { id: 41, term: 'Poco a poco', reading: 'ポーコ・ア・ポーコ', symbol: 'p.a.p.', category: '速度', lang: 'イタリア語', meaning: '少しずつ。', detail: '変化を緩やかに進める。', color: 'bg-orange-50' },

  // --- 奏法 (Technique) ---
  { id: 50, term: 'Legato', reading: 'レガート', symbol: '〜', category: '奏法', lang: 'イタリア語', meaning: 'なめらかに。', detail: '音の境目をなくし繋いで演奏。', color: 'bg-blue-100 text-blue-600' },
  { id: 51, term: 'Staccato', reading: 'スタッカート', symbol: '・', category: '奏法', lang: 'イタリア語', meaning: '短く切って。', detail: '音を切り離し軽快に跳ねる。', color: 'bg-indigo-100 text-indigo-600' },
  { id: 52, term: 'Tenuto', reading: 'テヌート', symbol: '-', category: '奏法', lang: 'イタリア語', meaning: '音を保って。', detail: '音を最後までしっかり響かせる。', color: 'bg-violet-100 text-violet-600' },
  { id: 53, term: 'Fermata', reading: 'フェルマータ', symbol: '𝄐', category: '奏法', lang: 'イタリア語', meaning: 'ほどよく延ばす。', detail: '一時停止して余韻を楽しむ。', color: 'bg-fuchsia-100 text-fuchsia-600' },
  { id: 54, term: 'Pizzicato', reading: 'ピッツィカート', symbol: 'pizz.', category: '奏法', lang: 'イタリア語', meaning: '弦を弾く。', detail: '指で弦をはじいて音を出す。', color: 'bg-amber-100' },
  { id: 55, term: 'Arco', reading: 'アルコ', symbol: 'arco', category: '奏法', lang: 'イタリア語', meaning: '弓で。', detail: '再び弓を使って演奏する。', color: 'bg-slate-200' },
  { id: 56, term: 'Glissando', reading: 'グリッサンド', symbol: 'gliss.', category: '奏法', lang: 'イタリア語', meaning: '滑らせて。', detail: '高さを連続的に変化させる。', color: 'bg-cyan-100' },
  { id: 57, term: 'Trill', reading: 'トリル', symbol: 'tr', category: '奏法', lang: 'イタリア語', meaning: '震わせて。', detail: '隣接音を高速で反復させる。', color: 'bg-yellow-50' },
  { id: 58, term: 'Mordent', reading: 'モルデント', symbol: 'mord.', category: '奏法', lang: 'イタリア語', meaning: '短く震。', detail: '隣の音を一往復させる装飾。', color: 'bg-orange-50' },
  { id: 59, term: 'Portamento', reading: 'ポルタメント', symbol: 'port.', category: '奏法', lang: 'イタリア語', meaning: '滑らか繋。', detail: '音の間を滑らせて移る。', color: 'bg-teal-50' },
  { id: 60, term: 'Tutti', reading: 'トゥッティ', symbol: 'tutti', category: '奏法', lang: 'イタリア語', meaning: '全員で。', detail: '合奏者全員での演奏。', color: 'bg-blue-200' },
  { id: 61, term: 'Solo', reading: 'ソロ', symbol: 'solo', category: '奏法', lang: 'イタリア語', meaning: '独奏。', detail: '一人の奏者が主役となる。', color: 'bg-yellow-200' },
  { id: 62, term: 'Divisi', reading: 'ディヴィジ', symbol: 'div.', category: '奏法', lang: 'イタリア語', meaning: '分かれて。', detail: '同じパートが別々の音を弾く。', color: 'bg-teal-50' },

  // --- 表情 (Expression) ---
  { id: 100, term: 'Dolce', reading: 'ドルチェ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '甘く。', detail: '優しく愛らしい表情で。', color: 'bg-pink-50 text-pink-400' },
  { id: 101, term: 'Cantabile', reading: 'カンタービレ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '歌うように。', detail: '旋律の美しさを強調する。', color: 'bg-indigo-50 text-indigo-500' },
  { id: 102, term: 'Agitato', reading: 'アジタート', symbol: null, category: '表情', lang: 'イタリア語', meaning: '激しく。', detail: '情熱的で興奮した表現。', color: 'bg-red-50 text-red-600' },
  { id: 103, term: 'Maestoso', reading: 'マエストーゾ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '堂々と。', detail: '荘厳で立派な雰囲気。', color: 'bg-slate-200 text-slate-700' },
  { id: 104, term: 'Tranquillo', reading: 'トランクィッロ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '静かに。', detail: '穏やかで平和な気分で。', color: 'bg-cyan-50 text-cyan-500' },
  { id: 105, term: 'Espressivo', reading: 'エスプレッシーヴォ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '表情豊かに。', detail: '感情をたっぷり込めて。', color: 'bg-rose-50 text-rose-600' },
  { id: 106, term: 'Grazioso', reading: 'グラツィオーゾ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '優雅に。', detail: '上品でしなやかな美しさ。', color: 'bg-purple-50 text-purple-500' },
  { id: 107, term: 'Misterioso', reading: 'ミステリオーゾ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '神秘的に。', detail: '不思議で謎めいた雰囲気。', color: 'bg-indigo-100 text-indigo-700' },
  { id: 108, term: 'Scherzando', reading: 'スケルツァンド', symbol: null, category: '表情', lang: 'イタリア語', meaning: 'おどけて。', detail: '戯れるようなユーモア。', color: 'bg-yellow-100 text-yellow-700' },
  { id: 109, term: 'Appassionato', reading: 'アパッショナート', symbol: null, category: '表情', lang: 'イタリア語', meaning: '熱情的に。', detail: '深い感情を込めて。', color: 'bg-red-200 text-red-700' },
  { id: 110, term: 'Brillante', reading: 'ブリランテ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '輝かしく。', detail: '宝石のように華麗に輝く。', color: 'bg-yellow-50 text-amber-600' },
  { id: 111, term: 'Animato', reading: 'アニマート', symbol: null, category: '表情', lang: 'イタリア語', meaning: '生き生きと。', detail: '活発に動く表情。', color: 'bg-orange-50 text-orange-500' },
  { id: 112, term: 'Risoluto', reading: 'リゾルート', symbol: null, category: '表情', lang: 'イタリア語', meaning: '決然と。', detail: '迷いのない意志の強さ。', color: 'bg-neutral-200 text-neutral-800' },
  { id: 113, term: 'Affettuoso', reading: 'アフェットゥオーゾ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '慈しんで。', detail: '優しい愛情あふれる表情。', color: 'bg-rose-100 text-rose-500' },
  { id: 114, term: 'Energico', reading: 'エネルジコ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '精力的に。', detail: 'パワフルで活力ある。', color: 'bg-orange-100 text-orange-800' },
  { id: 115, term: 'Giocoso', reading: 'ジョコーゾ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '楽しく。', detail: '陽気で愉快な気分。', color: 'bg-orange-100 text-orange-600' },
  { id: 116, term: 'Grandioso', reading: 'グランディオーゾ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '壮大に。', detail: '雄大でスケールの大きな。', color: 'bg-slate-100 text-slate-600' },
  { id: 117, term: 'Abbandonatamente', reading: 'アッバンドナタメンテ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '身を任せて。', detail: '抑制を解き自由に演奏。', color: 'bg-rose-50' },
  { id: 118, term: 'Bellicoso', reading: 'ベッリコーゾ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '戦うように。', detail: '攻撃的で勇ましい表情。', color: 'bg-red-600 text-white' },
  { id: 119, term: 'Smorfioso', reading: 'スモルフィオーゾ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '気気取って。', detail: '不自然におどけて見せる。', color: 'bg-pink-300' },
  { id: 120, term: 'Leggiero', reading: 'レッジェーロ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '軽快に。', detail: '羽根のように軽く演奏。', color: 'bg-cyan-100' },
  { id: 121, term: 'Serioso', reading: 'セリオーゾ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '真剣に。', detail: '真面目な面持ちで。', color: 'bg-slate-400 text-white' },
  { id: 122, term: 'Zeloso', reading: 'ゼローゾ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '熱心に。', detail: '一生懸命な様を表現。', color: 'bg-red-50' },
  { id: 123, term: 'Bizzarro', reading: 'ビッツァーロ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '風変わりな。', detail: '奇妙で独特な表現。', color: 'bg-stone-100' },
  { id: 124, term: 'Calmato', reading: 'カルマート', symbol: null, category: '表情', lang: 'イタリア語', meaning: '静まって。', detail: '落ち着きを取り戻す表情。', color: 'bg-blue-50' },
  { id: 125, term: 'Determinato', reading: 'デテルミナート', symbol: null, category: '表情', lang: 'イタリア語', meaning: '毅然として。', detail: '迷いのないはっきりした表現。', color: 'bg-indigo-300 text-white' },
  { id: 126, term: 'Elegante', reading: 'エレガンテ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '優雅に。', detail: '洗練された美しさ。', color: 'bg-purple-50' },
  { id: 127, term: 'Feroce', reading: 'フェローチェ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '荒々しく。', detail: '野性的な激しい力強さ。', color: 'bg-red-700 text-white' },
  { id: 128, term: 'Gentile', reading: 'ジェンティーレ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '上品に。', detail: '洗練された親切な様。', color: 'bg-cyan-50' },
  { id: 129, term: 'Lamentoso', reading: 'ラメントーゾ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '悲しげに。', detail: '嘆くような重い表情。', color: 'bg-slate-400 text-white' },
  { id: 130, term: 'Nobile', reading: 'ノービレ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '高貴に。', detail: '気高く誇り高い。', color: 'bg-yellow-50' },
  { id: 131, term: 'Pastoral', reading: 'パストラル', symbol: null, category: '表情', lang: 'フランス語', meaning: '田園的に。', detail: 'のどかな牧歌的風景。', color: 'bg-green-100' },
  { id: 132, term: 'Pesante', reading: 'ペザンテ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '重々しく。', detail: '力強い重さを表現。', color: 'bg-stone-500 text-white' },
  { id: 133, term: 'Religioso', reading: 'レリジオーゾ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '宗教的に。', detail: '厳かな祈りの雰囲気。', color: 'bg-neutral-100' },
  { id: 134, term: 'Semplice', reading: 'センプリチェ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '単純に。', detail: 'ありのままに素直に。', color: 'bg-neutral-50' },
  { id: 135, term: 'Soave', reading: 'ソアーヴェ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '柔和に。', detail: '感じの良い愛想。', color: 'bg-pink-50' },
  { id: 136, term: 'Tenero', reading: 'テーネロ', symbol: null, category: '表情', lang: 'イタリア語', meaning: '優しく。', detail: '愛情深い柔らかな表現。', color: 'bg-rose-50' },

  // --- 構成 (Structure) ---
  { id: 200, term: 'Fine', reading: 'フィーネ', symbol: 'Fine', category: '構成', lang: 'イタリア語', meaning: '終わり。', detail: '楽曲の終了地点。', color: 'bg-slate-300 text-slate-800' },
  { id: 201, term: 'Da Capo', reading: 'ダ・カーポ', symbol: 'D.C.', category: '構成', lang: 'イタリア語', meaning: '最初へ。', detail: '冒頭に戻る。', color: 'bg-neutral-100 text-neutral-600' },
  { id: 202, term: 'Dal Segno', reading: 'ダル・セーニョ', symbol: 'D.S.', category: '構成', lang: 'イタリア語', meaning: 'セーニョへ。', detail: '記号まで戻る。', color: 'bg-neutral-200 text-neutral-700' },
  { id: 203, term: 'Coda', reading: 'コーダ', symbol: '𝄌', category: '構成', lang: 'イタリア語', meaning: '結び。', detail: '独立した終結部。', color: 'bg-slate-200 text-slate-600' },
  { id: 204, term: 'Segno', reading: 'セーニョ', symbol: '𝄋', category: '構成', lang: 'イタリア語', meaning: '標識。', detail: '繰り返しの印。', color: 'bg-neutral-100 text-neutral-500' },
  { id: 205, term: 'Repeat', reading: 'リピート', symbol: ':||', category: '構成', lang: '英語', meaning: '繰り返し。', detail: '指定区間を再演。', color: 'bg-neutral-50 text-neutral-400' },
  { id: 206, term: 'Attacca', reading: 'アッタッカ', symbol: 'Attacca', category: '構成', lang: 'イタリア語', meaning: '続けて。', detail: '休みなく次へ。', color: 'bg-red-50 text-red-500' },
];

// --- 拡張用ダミーデータ (実数維持) ---
const EXTRA_TERMS = Array.from({ length: 110 }).map((_, i) => ({
  id: 1000 + i,
  term: `Music Theory ${i + 1}`,
  reading: `がくてんようご ${i + 1}`,
  symbol: null,
  category: i % 2 === 0 ? '楽曲形式' : '楽典',
  lang: 'イタリア語',
  meaning: '音楽の基本理論。',
  detail: '演奏を深めるための重要な知識です。',
  color: 'bg-slate-50 text-slate-400'
}));

export const FINAL_TERMS = [...INITIAL_TERMS, ...EXTRA_TERMS];
